shallow_clone: true

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "10"

branches:
  only:
  - master

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm i

build_script:
  - npm run build

test_script:
  - npm run test